# -*- coding: utf-8 -*-
"""LGMVIP- DataScience-BEGINNER LEVEL TASK-Task-4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1dPB7co_KuzkdOaB-IoUeKSlysfjtBoqy
"""

import cv2
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow

img=cv2.imread("/content/photo.jpg")

print("ORIGINl IMAGE",img)

plt.figure(figsize=(8, 8))
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Original Image')
plt.axis('off')
plt.show()

# Convert the image to grayscale
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

plt.figure(figsize=(8, 8))
plt.imshow(gray_image, cmap='gray')
plt.title('Grayscale Image')
plt.axis('off')
plt.show()

# Invert the grayscale image
inverted_image = 255 - gray_image

plt.figure(figsize=(8, 8))
plt.imshow(inverted_image, cmap='gray')
plt.title('Inverted Image')
plt.axis('off')
plt.show()

# Apply Gaussian blur to the inverted image
blurred_image = cv2.GaussianBlur(inverted_image, (21, 21), 0)

plt.figure(figsize=(8, 8))
plt.imshow(blurred_image, cmap='gray')
plt.title('Blurred Image')
plt.axis('off')
plt.show()

# Invert the blurred image
inverted_blurred_image = 255 - blurred_image

plt.figure(figsize=(8, 8))
plt.imshow(inverted_blurred_image , cmap='gray')
plt.title('inverted_blurred_image ')
plt.axis('off')
plt.show()

# Create the pencil sketch by blending the grayscale and inverted blurred image
pencil_sketch = cv2.divide(gray_image, inverted_blurred_image, scale=256.0)

# Display the pencil sketch
plt.figure(figsize=(8, 8))
plt.imshow(pencil_sketch, cmap='gray')
plt.title('Pencil Sketch')
plt.axis('off')
plt.show()

plt.figure(figsize=(8, 8))
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB))
plt.title('Original Image')
plt.axis('off')
plt.show()
plt.figure(figsize=(8, 8))
plt.imshow(gray_image, cmap='gray')
plt.title('Grayscale Image')
plt.axis('off')
plt.show()
plt.figure(figsize=(8, 8))
plt.imshow(inverted_image, cmap='gray')
plt.title('Inverted Image')
plt.axis('off')
plt.show()
plt.figure(figsize=(8, 8))
plt.imshow(blurred_image, cmap='gray')
plt.title('Blurred Image')
plt.axis('off')
plt.show()
plt.figure(figsize=(8, 8))
plt.imshow(inverted_blurred_image , cmap='gray')
plt.title('inverted_blurred_image ')
plt.axis('off')
plt.show()
plt.figure(figsize=(8, 8))
plt.imshow(pencil_sketch, cmap='gray')
plt.title('Pencil Sketch')
plt.axis('off')
plt.show()

from IPython.display import display, Image
plt.figure(figsize=(25,25))
plt.subplot(1,6,1)
plt.imshow(img)
plt.axis("off")
plt.title("Original Image")
plt.subplot(1,6,2)
plt.imshow(gray_image,cmap="gray")
plt.axis("off")
plt.title("GrayScale Image")
plt.subplot(1,6,3)
plt.imshow(inverted_image,cmap="gray")
plt.axis("off")
plt.title("Inverted Image")
plt.subplot(1,6,4)
plt.imshow(blurred_image,cmap="gray")
plt.axis("off")
plt.title("Smoothen Image")
plt.subplot(1,6,5)
plt.imshow(inverted_blurred_image , cmap='gray')
plt.title('inverted_blurred_image ')
plt.axis('off')
plt.subplot(1,6,6)
plt.imshow(pencil_sketch,cmap="gray")
plt.axis("off")
plt.title("Final Sketch Image")
plt.show()